variables:
  SOLUTION_FILE_PATH: ./src/
  DOCKER_TLS_CERTDIR: ""
  CI_DEBUG_TRACE: "true"

stages:
  - build
  - test
  - docker

build:
  stage: build
  image: registry.cn-shenzhen.aliyuncs.com/dotnet-vincent/sdk:5.0
  script: 
    - dotnet restore $SOLUTION_FILE_PATH
    - dotnet build --no-restore $SOLUTION_FILE_PATH
  tags:
    - build

test:
  stage: test
  image: registry.cn-shenzhen.aliyuncs.com/dotnet-vincent/sdk:5.0
  script:
    - dotnet restore $SOLUTION_FILE_PATH
    - dotnet test --no-restore $SOLUTION_FILE_PATH
  tags:
    - test

docker:
  image: docker:dind
  stage: docker
  services:
  - name: docker:dind
    command:
      [
        '--insecure-registry=192.168.3.54:5050',
      ]
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest ./src/
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master
  tags:
    - build-docker-image

