pipeline {
    agent any 
    stages {
        stage('编译解决方案') {
            steps {
               sh 'cd src'
               sh 'dotnet build DockerDemo.sln'
            }
        }
        stage('运行单元测试') {
            steps {
                echo 'Hello world2!' 
            }
        }      
        stage('生成docker镜像') {
            steps {
                echo '生成docker image'
                echo '列出文件'
                 sh "ls" 
            }
        }      
    }
}
